/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pis.hue1;

public class App {
    public static void main(String[] args) {
        CodecGUI.main(new String[0]);
    }
}
